name: link_nest
description: A simple offline app to store and organize LinkedIn posts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.6
  flutter_bloc_hooks:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  url_launcher: ^6.3.1
  equatable: ^2.0.5
  path_provider: ^2.1.0
  uuid: ^3.0.7
  # flutter_inappwebview: ^5.7.2+3
  webview_flutter: ^4.4.4
  share_plus: ^7.2.1
  flutter_staggered_animations: ^1.1.1
  iconsax_flutter: ^1.0.0
  flutter_html: ^3.0.0-beta.2
  webview_flutter_web: ^0.2.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.3

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # Commenting out fonts section since font files don't exist yet
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300 